{
 "title": "Panel Sensor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "🔽 Presión Atmosférica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mediciones\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"presion\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "💧 Humedad Relativa",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mediciones\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humedad\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "🌡️ Temperatura en Tiempo Real",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mediciones\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura\")\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}